#!/usr/bin/env python3
"""Schreibt alle Nachschlag-Texte so um, dass sie ihr Subjekt selbst nennen."""
import json, pathlib

NEU = {
1:"Von einem Flug zur Andromedagalaxie gäbe es keine sinnvolle Rückkehr: Auf der Erde wären nach Hin- und Rückflug 5 Millionen Jahre vergangen.",
2:"Der Flug zu Proxima Centauri scheitert nicht an der Zeit, sondern an der Energie: Ein Schiff auf nahezu Lichtgeschwindigkeit zu beschleunigen übersteigt jede heutige Vorstellung.",
3:"Für die 100.000 Lichtjahre quer durch die Milchstraße bräuchte die Sonde Voyager 1 rund 1,7 Milliarden Jahre.",
4:"Warum die Venus so langsam rotiert, ist ungeklärt. Vermutlich hat ein gewaltiger Einschlag in der Frühzeit ihre Drehung fast gestoppt.",
5:"Die Sonne wäre von der Venusoberfläche aus allerdings nie zu sehen: Die Wolkendecke des Planeten ist dauerhaft geschlossen.",
6:"Von der restlichen Masse des Sonnensystems entfällt wiederum der größte Teil auf Jupiter allein.",
7:"Trotz dieses gewaltigen Umsatzes hat die Sonne bisher erst etwa 0,03 % ihrer Gesamtmasse verloren.",
8:"Würde der Sonnenkern heute erlöschen, leuchtete die Sonnenoberfläche noch sehr lange weiter. Nur Neutrinos verrieten es innerhalb von 8 Minuten.",
9:"Auch der nächste Stern, Proxima Centauri, ist ein Roter Zwerg – trotz nur 4,2 Lichtjahren Abstand mit bloßem Auge unsichtbar.",
10:"Die kleinsten Roten Zwerge sind kaum größer als der Planet Saturn.",
11:"Der dichteste Körper im Sonnensystem ist übrigens die Erde mit 5,5 g/cm³.",
12:"Saturns Ringe bestehen fast vollständig aus Wassereis. Die einzelnen Brocken reichen von Staubkorn- bis Hausgröße.",
13:"Saturns Ringe standen zuletzt im Frühjahr 2025 exakt auf der Kante. Das nächste Mal passiert das Ende der 2030er Jahre.",
14:"Ein Teelöffel Wasser wiegt dagegen 5 Gramm. Neutronensterne bestehen aus dem dichtesten bekannten Material im Universum.",
15:"So schnelle Pulsare heißen Millisekundenpulsare. Sie wurden von einem Begleitstern „aufgezogen“, der Materie auf sie übertrug.",
16:"Neutronensterne wurden 1967 durch ein extrem regelmäßiges Radiosignal entdeckt, das man kurz für außerirdisch hielt.",
17:"Tatsächlich wird die Sonne nie ein Schwarzes Loch. Dafür ist sie zu leicht – sie endet als Weißer Zwerg.",
18:"Die Entstehung von Diamanten unter solchem Druck ließ sich im Labor mit Laser-Schockwellen tatsächlich nachstellen.",
19:"Vermutlich hat ein erdgroßer Körper den Uranus in der Frühzeit des Sonnensystems umgestoßen.",
20:"Neptun wurde zuerst berechnet und dann gefunden: aus unerklärlichen Störungen der Uranusbahn.",
21:"Plutos Bahn ist so langgestreckt, dass er zeitweise näher an der Sonne steht als Neptun – zuletzt von 1979 bis 1999.",
22:"Um als Stern zu zünden, hätte Jupiter etwa das 80-Fache seiner heutigen Masse gebraucht.",
23:"Am Wackeln eines Sterns erkennt man umgekehrt, dass ihn ein schwerer Planet umkreist. So wurden viele Exoplaneten entdeckt.",
24:"Die Eintauchsonde der Galileo-Mission hielt in Jupiters Atmosphäre 1995 knapp 58 Minuten durch.",
25:"So groß werden konnte der Olympus Mons, weil der Mars keine Plattentektonik hat: Der Vulkan blieb Milliarden Jahre über derselben Magmaquelle.",
26:"In den Valles Marineris auf dem Mars würde der Grand Canyon gleich mehrfach verschwinden.",
27:"Auf dem Mars ist der Himmel rötlich und der Sonnenuntergang blau – auf der Erde ist es genau umgekehrt.",
28:"Auf Merkur könnte ein Beobachter die Sonne zeitweise sogar rückwärts über den Himmel laufen sehen.",
29:"Erste Hinweise auf Eis an den Merkurpolen lieferte 1992 eine Radarmessung von der Erde aus.",
30:"Der Bodendruck auf der Venus beträgt das 92-Fache des irdischen – wie in 900 Metern Meerestiefe.",
31:"Regen, der verdunstet, bevor er den Boden erreicht, heißt Virga. Auch auf der Erde kommt das vor – dort allerdings mit Wasser.",
32:"Die Sonde Huygens landete 2005 auf Titan. Es ist bis heute die fernste Landung der Raumfahrtgeschichte.",
33:"In den Fontänen von Enceladus fand man organische Moleküle. Der Mond gilt als einer der besten Kandidaten für Leben im Sonnensystem.",
34:"Alle Asteroiden des Gürtels zusammen wögen weniger als 5 % des Erdmonds.",
35:"Der Abstand zum Mond wird per Laser an Reflektoren gemessen, die die Apollo-Missionen dort aufgestellt haben.",
36:"Die früher schnellere Erddrehung ist an fossilen Gezeitenablagerungen und an Wachstumsstreifen versteinerter Korallen nachweisbar.",
37:"Nur der ständige Beschuss durch winzige Mikrometeoriten trägt die Mondoberfläche ab – extrem langsam.",
38:"Zwei Drittel dieser aneinandergereihten Planetendurchmesser entfallen allein auf Jupiter und Saturn.",
39:"Voyager 1 funkt mit rund 20 Watt Sendeleistung – weniger als eine Kühlschranklampe.",
40:"Der äußere Rand der Oortschen Wolke liegt vermutlich bei einem Lichtjahr – ein Viertel des Weges zum nächsten Stern.",
41:"Nach Sonne und Mond ist die ISS das hellste Objekt am Himmel – mit bloßem Auge gut zu verfolgen.",
42:"Der Rand des beobachtbaren Universums ist keine Wand, sondern ein Horizont: Von dahinter hat uns bislang noch kein Licht erreicht.",
43:"Die kosmische Hintergrundstrahlung wurde 1964 zufällig entdeckt. Die Forscher hielten das Störsignal zunächst für Taubendreck in ihrer Antenne.",
44:"Um überhaupt einzelne Neutrinos nachzuweisen, baut man Detektoren tief unter Bergen oder im antarktischen Eis.",
45:"Zählen kann man die Sterne des Universums natürlich nicht. Man rechnet über die Zahl der Galaxien und ihre typische Sternenzahl.",
46:"Der Vergleich zwischen Bäumen und Sternen hinkt trotzdem: Im gesamten Universum gibt es unvorstellbar viel mehr Sterne als Bäume auf der Erde.",
47:"Die Sonne wird die Verschmelzung von Milchstraße und Andromeda noch erleben – sie leuchtet danach noch etwa eine weitere Milliarde Jahre.",
48:"Die Andromedagalaxie steht am Herbsthimmel hoch. Schon ein Fernglas zeigt sie als deutliches längliches Oval.",
49:"Vor 4.700 Jahren war Thuban im Sternbild Drache der Polarstern. Die Ägypter richteten ihre Pyramiden danach aus.",
50:"Bestätigt wurde die Entstehung von Gold 2017, als bei einer beobachteten Neutronenstern-Kollision schwere Elemente nachgewiesen wurden.",
51:"Im Fachjargon heißt das Big-Freeze-Szenario auch Wärmetod – obwohl es dabei eiskalt zugeht.",
52:"Im Big-Rip-Modell hätte das Universum ein Ablaufdatum – je nach Annahme in etwa 20 Milliarden Jahren.",
53:"Ein solcher Kollaps gilt heute als unwahrscheinlich: Die Ausdehnung des Universums wird nicht langsamer, sondern schneller.",
54:"Ein Problem der Zyklus-Idee: Jeder neue Durchgang müsste die Unordnung seines Vorgängers erben.",
55:"Ob unser Vakuum stabil ist, hängt an der Masse des Higgs-Teilchens. Ihr gemessener Wert liegt unangenehm nah an der Grenze zur Instabilität.",
56:"In einem vollkommen gleichmäßigen Universum wäre auch Zeit nicht mehr messbar – es gäbe schlicht kein Ereignis mehr.",
57:"Die letzten leuchtenden Sterne wären Rote Zwerge, die ihren Brennstoff extrem sparsam verbrauchen.",
58:"Die Ära der Schwarzen Löcher dauert rund 10<sup>67</sup> Jahre – unvorstellbar viel länger als alles, was davor passiert ist.",
59:"Beobachtet wurde noch kein einziger Protonenzerfall. Riesige Detektoren in Japan warten seit Jahrzehnten darauf.",
60:"Für Beobachter in dieser fernen Zukunft wäre die eigene Galaxie schlicht das ganze Universum.",
61:"Dass das Universum einen Anfang hatte, erscheint uns heute selbstverständlich. Für spätere Beobachter wäre es prinzipiell unbeweisbar.",
62:"Fred Hoyle vertrat die Steady-State-Theorie, nach der das Universum immer schon so aussah wie heute.",
63:"Bei einem Schwarzen Loch von 10 Sonnenmassen liegt der Ereignishorizont bei rund 30 km Radius.",
64:"Für den Fallenden selbst dauert der Sturz in ein Schwarzes Loch nur Sekundenbruchteile.",
65:"Aus dem Inneren eines Schwarzen Lochs sieht man den Sternenhimmel weiterhin – nur zunehmend verzerrt.",
66:"Den Begriff Spaghettifizierung prägte Stephen Hawking in seinem Buch „Eine kurze Geschichte der Zeit“.",
67:"Beim Schwarzen Loch Sagittarius A* im Zentrum der Milchstraße wäre ein solcher unversehrter Eintritt möglich.",
68:"Im Inneren eines Schwarzen Lochs bringt selbst stärkstes Beschleunigen nichts – jede Bewegung verkürzt die verbleibende Zeit sogar.",
69:"Die Hawking-Strahlung verbindet erstmals Schwerkraft, Quantentheorie und Wärmelehre – bis heute ein Ausgangspunkt moderner Physik.",
70:"Das gilt nur, wenn nichts mehr hineinfällt. Heute wachsen Schwarze Löcher noch deutlich schneller, als sie verdampfen.",
71:"Winzige Schwarze Löcher aus der Frühzeit des Universums müssten gerade jetzt explodieren – gesucht, aber nie gefunden.",
72:"Was mit der Information über das geschieht, was ein Schwarzes Loch verschluckt hat, ist bis heute ungelöst – das Informationsparadoxon.",
73:"Für die über 30 Jahre laufende Vermessung der Sterne im Milchstraßenzentrum gab es 2020 den Physik-Nobelpreis.",
74:"Von der Erde aus gesehen ist das Schwarze Loch im Milchstraßenzentrum so klein wie ein Apfel auf dem Mond.",
75:"Für dieses Bild wurden Radioteleskope rund um die Welt zusammengeschaltet. Die Datenmenge war so groß, dass die Festplatten per Flugzeug transportiert wurden.",
76:"Der hellste bekannte Quasar leuchtet so stark wie mehrere hundert Billionen Sonnen.",
77:"Grund ist, dass der Ereignishorizont proportional zur Masse wächst, das eingeschlossene Volumen aber mit der dritten Potenz.",
78:"Für den ersten Nachweis von Gravitationswellen gab es 2017 den Physik-Nobelpreis.",
79:"Um Störungen auszuschließen, betreibt LIGO zwei baugleiche Detektoren im Abstand von rund 3.000 km.",
80:"Der Effekt heißt Frame-Dragging. Selbst die rotierende Erde erzeugt ihn – winzig, aber im Orbit messbar.",
81:"Für seine Arbeiten zu Schwarzen Löchern erhielt Roger Penrose 2020 den Physik-Nobelpreis.",
82:"Um in ein Schwarzes Loch zu fallen, muss man ziemlich genau zielen. Das meiste Material geht stattdessen in eine Umlaufbahn.",
83:"Ohne Sonnenlicht fiele die Temperatur auf der Erde innerhalb weniger Wochen unter minus 100 °C.",
84:"Auf der ISS lässt gleichzeitig die schwächere Schwerkraft in 400 km Höhe die Zeit schneller laufen – der Geschwindigkeitseffekt gewinnt knapp.",
85:"Ein Astronaut merkt von der Zeitdilatation nichts. Der Effekt zeigt sich nur beim Vergleich hochpräziser Uhren.",
86:"Die relativistische Korrektur steckt fest einprogrammiert in jedem GPS-Empfänger – auch in jedem Handy.",
87:"GPS-Satellitenuhren werden deshalb schon vor dem Start bewusst etwas langsamer eingestellt.",
88:"Der Nachweis gelang 2010 erstmals bei nur 33 Zentimetern Höhenunterschied zwischen zwei Atomuhren.",
89:"Für denjenigen, der in ein Schwarzes Loch fällt, vergeht die Zeit dagegen ganz normal weiter.",
90:"Nach zehn Jahren an Bord eines solchen Schiffs käme man auf eine Erde zurück, auf der 2.240 Jahre vergangen sind.",
91:"Der Haken solcher Reisen: Nahe der Lichtgeschwindigkeit hätte schon ein einzelnes Staubkorn die Wirkung einer Explosion.",
92:"Ein Rückweg wäre bei solchen Reisen sinnlos: Die Heimat, die man verlassen hat, existierte längst nicht mehr.",
93:"Aus Sicht des Myons dehnt sich nicht die Zeit – für es schrumpft die Atmosphäre.",
94:"Das Zwillingsparadoxon wurde 1971 mit Atomuhren in Linienflugzeugen überprüft und bestätigt.",
95:"Ein Beobachter auf einem Neutronenstern sähe das übrige Universum entsprechend im Zeitraffer.",
96:"Der Nachweis der Gravitationsrotverschiebung gelang schon 1959 auf der Erde – in einem nur 22 Meter hohen Turm.",
97:"Der Urknall fand deshalb nicht an einem bestimmten Ort statt, sondern überall auf einmal.",
98:"Das Licht solcher Galaxien kann uns trotzdem erreichen – vorausgesetzt, es ist früh genug losgeflogen.",
99:"Dunkle Materie verrät sich dadurch, dass Galaxien schneller rotieren, als ihre sichtbare Masse erlaubt.",
100:"Die Entdeckung der beschleunigten Ausdehnung brachte 2011 den Physik-Nobelpreis – und ein Rätsel, das bis heute ungelöst ist.",
}

p = pathlib.Path(__file__).parent / "facts.json"
d = json.loads(p.read_text(encoding="utf-8"))
geaendert = 0
for k in d["karten"]:
    neu = NEU[k["nr"]]
    if neu != k["nachschlag"]:
        k["nachschlag"] = neu
        geaendert += 1
assert len(NEU) == 100 and set(NEU) == {k["nr"] for k in d["karten"]}
p.write_text(json.dumps(d, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"{geaendert} von 100 Nachschlag-Texten überarbeitet.")
